<div class="layer clearfix">

    <label class="left" for="form_geburtsland">

        <div class="size full">
            <div class="headline">
                Geburtsland
            </div>
            <div class="input dropdown">
                <i class="fa fa-caret-down"></i>
                <select id="form_geburtsland" class="hidden" name="form_geburtsland">
                    <option value="">Bitte wählen</option>
                    <option value="AF">Afghanistan</option>
                    <option value="EG">Ägypten</option>
                    <option value="AL">Albanien</option>
                    <option value="DZ">Algerien</option>
                    <option value="AN">Andorra</option>
                    <option value="AO">Angola</option>
                    <option value="AG">Antigua und Barbuda</option>
                    <option value="GQ">Äquatorialguinea</option>
                    <option value="AR">Argentinien</option>
                    <option value="AM">Armenien</option>
                    <option value="AZ">Aserbaidschan</option>
                    <option value="ET">Äthiopien</option>
                    <option value="AU">Australien</option>
                    <option value="BS">Bahamas</option>
                    <option value="BH">Bahrain</option>
                    <option value="BD">Bangladesch</option>
                    <option value="BB">Barbados</option>
                    <option value="BY">Belarus (vormals Weißrussland)</option>
                    <option value="BE">Belgien</option>
                    <option value="BZ">Belize</option>
                    <option value="BJ">Benin</option>
                    <option value="BT">Bhutan</option>
                    <option value="BO">Bolivien</option>
                    <option value="BA">Bosnien und Herzegowina</option>
                    <option value="BW">Botsuana</option>
                    <option value="BR">Brasilien</option>
                    <option value="BN">Brunei Darussalam</option>
                    <option value="BG">Bulgarien</option>
                    <option value="BF">Burkina Faso</option>
                    <option value="BI">Burundi</option>
                    <option value="CL">Chile</option>
                    <option value="CN">China</option>
                    <option value="CR">Costa Rica</option>
                    <option value="CI">Côte d'Ivoire (vormals Elfenbeinküste)</option>
                    <option value="DK">Dänemark</option>
                    <option selected="selected" value="DE">Deutschland</option>
                    <option value="DM">Dominica</option>
                    <option value="DO">Dominikanische Republik</option>
                    <option value="DJ">Dschibuti</option>
                    <option value="EC">Ecuador</option>
                    <option value="SV">El Salvador</option>
                    <option value="ER">Eritrea</option>
                    <option value="EE">Estland</option>
                    <option value="FJ">Fidschi</option>
                    <option value="FI">Finnland</option>
                    <option value="FR">Frankreich</option>
                    <option value="GA">Gabun</option>
                    <option value="GM">Gambia</option>
                    <option value="GE">Georgien</option>
                    <option value="GH">Ghana</option>
                    <option value="GD">Grenada</option>
                    <option value="GR">Griechenland</option>
                    <option value="GB">Großbritannien und Nordirland</option>
                    <option value="GT">Guatemala</option>
                    <option value="GN">Guinea</option>
                    <option value="GW">Guinea-Bissau</option>
                    <option value="GY">Guyana</option>
                    <option value="HT">Haiti</option>
                    <option value="HN">Honduras</option>
                    <option value="IN">Indien</option>
                    <option value="ID">Indonesien</option>
                    <option value="IQ">Irak</option>
                    <option value="IR">Iran</option>
                    <option value="IE">Irland</option>
                    <option value="IS">Island</option>
                    <option value="IL">Israel</option>
                    <option value="IT">Italien</option>
                    <option value="JM">Jamaika</option>
                    <option value="JP">Japan</option>
                    <option value="YE">Jemen</option>
                    <option value="JO">Jordanien</option>
                    <option value="KH">Kambodscha</option>
                    <option value="CM">Kamerun</option>
                    <option value="CA">Kanada</option>
                    <option value="CV">Kap Verde</option>
                    <option value="KZ">Kasachstan</option>
                    <option value="QA">Katar</option>
                    <option value="KE">Kenia</option>
                    <option value="KG">Kirgisistan</option>
                    <option value="KI">Kiribati</option>
                    <option value="CO">Kolumbien</option>
                    <option value="KM">Komoren</option>
                    <option value="CD">Kongo (Demokratische Republik)</option>
                    <option value="CG">Kongo (Republik)</option>
                    <option value="KP">Korea (Nord, Dem. Volksrepublik)</option>
                    <option value="KR">Korea (Süd, Republik)</option>
                    <option value="HR">Kroatien</option>
                    <option value="CU">Kuba</option>
                    <option value="KW">Kuwait</option>
                    <option value="LA">Laos</option>
                    <option value="LS">Lesotho</option>
                    <option value="LV">Lettland</option>
                    <option value="LB">Libanon</option>
                    <option value="LR">Liberia</option>
                    <option value="LY">Libyen</option>
                    <option value="LI">Liechtenstein</option>
                    <option value="LT">Litauen</option>
                    <option value="LU">Luxemburg</option>
                    <option value="MG">Madagaskar</option>
                    <option value="MW">Malawi</option>
                    <option value="MY">Malaysia</option>
                    <option value="MV">Malediven</option>
                    <option value="ML">Mali</option>
                    <option value="MT">Malta</option>
                    <option value="MA">Marokko</option>
                    <option value="MH">Marshallinseln</option>
                    <option value="MR">Mauretanien</option>
                    <option value="MU">Mauritius</option>
                    <option value="MK">Mazedonien</option>
                    <option value="MX">Mexiko</option>
                    <option value="FM">Mikronesien</option>
                    <option value="MD">Moldau, Republik</option>
                    <option value="MC">Monaco</option>
                    <option value="MN">Mongolei</option>
                    <option value="ME">Montenegro</option>
                    <option value="MZ">Mosambik</option>
                    <option value="MM">Myanmar (vormals Birma)</option>
                    <option value="NA">Namibia</option>
                    <option value="NR">Nauru</option>
                    <option value="NP">Nepal</option>
                    <option value="NZ">Neuseeland</option>
                    <option value="NI">Nicaragua</option>
                    <option value="NL">Niederlande</option>
                    <option value="NE">Niger</option>
                    <option value="NG">Nigeria</option>
                    <option value="NO">Norwegen</option>
                    <option value="OM">Oman</option>
                    <option value="AT">Österreich</option>
                    <option value="TL">Osttimor</option>
                    <option value="PK">Pakistan</option>
                    <option value="PW">Palau (vormals Belau)</option>
                    <option value="PA">Panama</option>
                    <option value="PG">Papua-Neuguinea</option>
                    <option value="PY">Paraguay</option>
                    <option value="PE">Peru</option>
                    <option value="PH">Philippinen</option>
                    <option value="PL">Polen</option>
                    <option value="PT">Portugal</option>
                    <option value="RW">Ruanda</option>
                    <option value="RO">Rumänien</option>
                    <option value="RU">Russische Föderation</option>
                    <option value="EH">Sahara, Demokratische Arabische Republik</option>
                    <option value="SB">Salomonen</option>
                    <option value="ZM">Sambia</option>
                    <option value="WS">Samoa</option>
                    <option value="SM">San Marino</option>
                    <option value="ST">São Tomé und Príncipe</option>
                    <option value="SA">Saudi-Arabien</option>
                    <option value="SE">Schweden</option>
                    <option value="CH">Schweiz</option>
                    <option value="SN">Senegal</option>
                    <option value="RS">Serbien</option>
                    <option value="SC">Seychellen</option>
                    <option value="SL">Sierra Leone</option>
                    <option value="ZW">Simbabwe</option>
                    <option value="SG">Singapur</option>
                    <option value="SK">Slowakei</option>
                    <option value="SI">Slowenien</option>
                    <option value="SO">Somalia</option>
                    <option value="ES">Spanien</option>
                    <option value="LK">Sri Lanka</option>
                    <option value="KN">St. Kitts und Nevis</option>
                    <option value="LC">St. Lucia</option>
                    <option value="VC">St. Vincent und die Grenadinen</option>
                    <option value="ZA">Südafrika</option>
                    <option value="SD">Sudan</option>
                    <option value="SR">Suriname</option>
                    <option value="SZ">Swasiland</option>
                    <option value="SY">Syrien</option>
                    <option value="TJ">Tadschikistan</option>
                    <option value="TW">Taiwan</option>
                    <option value="TZ">Tansania</option>
                    <option value="TH">Thailand</option>
                    <option value="TG">Togo</option>
                    <option value="TO">Tonga</option>
                    <option value="TT">Trinidad und Tobago</option>
                    <option value="TD">Tschad</option>
                    <option value="CZ">Tschechische Republik</option>
                    <option value="TN">Tunesien</option>
                    <option value="TR">Türkei</option>
                    <option value="TM">Turkmenistan</option>
                    <option value="TV">Tuvalu</option>
                    <option value="UG">Uganda</option>
                    <option value="UA">Ukraine</option>
                    <option value="HU">Ungarn</option>
                    <option value="UY">Uruguay</option>
                    <option value="US">USA</option>
                    <option value="UZ">Usbekistan</option>
                    <option value="VU">Vanatu</option>
                    <option value="VA">Vatikanstadt</option>
                    <option value="VE">Venezuela</option>
                    <option value="AE">Vereinigte Arabische Emirate</option>
                    <option value="VN">Vietnam</option>
                    <option value="CF">Zentralafrikanische Republik</option>
                    <option value="CY">Zypern</option>
                </select>
            </div>
        </div>

    </label>

    <div class="right">
        <?php include( 'forms/helptip.php' ) ?>
    </div>

</div>